# ========================================================
- name: "字符串"
  color: "800080"
  description: "1010#字符串"
  
- name: "数组"
  color: "800080"
  description: "1010#数组"

- name: "数组"
  color: "800080"
  description: "1010#数组"
