name: Gen-Labels
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Synchronize labels
        uses: julbme/gh-action-manage-label@v1
        with:
          from: .github/config/labels.yml
          skip_delete: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
